### ISSUE TITLE
Updating Moodle version

### ISSUE THREAD

**Issue by jchavezb-37** [aws-samples/aws-refarch-moodle#47]
How can I update a new Moodle version without loss data?.  Only I must to update the stack modifing the yaml file?

**Comment by vrioux** [comment]
Hi, thank you for opening this issue. In a nutshell, upgrading the Moodle version after deploying this stack involves updating the CodeCommit repository with the appropriate files. You should also setup a maintenance window in order to realize any database schema upgrades before allowing trafic to the Moodle instance.

You can follow the Moodle original documentation regarding git upgrades, as the process is generally the same. https://docs.moodle.org/402/en/Git_for_Administrators#Updating_your_installation_with_minor_releases

Please let me know if you need further help with this.

**Comment by jchavezb-37** [comment]
Very thanks Vincent!
